version: '3.8'
services:
  app:
    build: .
    container_name: verloop-container
    image: verloop-img
    command: uvicorn src.main:app --host 0.0.0.0 --port 80 --reload
    ports: 
      - 80:80
    stdin_open: true
    tty: true
    env_file:
      - .env
    volumes:
      - ./src:/code/src